before_install:
  - go get -u github.com/stretchr/testify/require

  # Install code coverage / coveralls tooling
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/modocache/gover
  - go get -u github.com/mattn/goveralls

  # Unpack and start the Stripe API stub so that the test suite can talk to it
  - |
    if [ ! -d "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}" ]; then
      mkdir -p stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}/
      curl -L "https://github.com/stripe/stripe-mock/releases/download/v${STRIPE_MOCK_VERSION}/stripe-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz" -o "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz"
      tar -zxf "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz" -C "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}/"
    fi
  - |
    stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}/stripe-mock > /dev/null &
    STRIPE_MOCK_PID=$!

cache:
  directories:
    - stripe-mock

env:
  global:
    - STRIPE_MOCK_VERSION=0.4.0

go:
  - 1.7
  - 1.8
  - 1.9
  - tip

language: go

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - make
  - make coverage

after_script:
  # Merge all coverage reports located in subdirectories and put them under: gover.coverprofile
  - gover
  # Send code coverage report to coveralls.io
  - goveralls -service=travis-ci -coverprofile=gover.coverprofile

sudo: false
